config/routes.rb
Rails.application.routes.draw do

  root 'trades#index'

  get '/login.html', :controller => 'login', :action => :new, :as => :login
  post '/authenticate.html', :controller => 'login', :action => :create, :as => :authenticate
  delete '/logout.html', :controller => 'login', :action => :destroy, :as => :logout

  resources :trades
  resources :flavours

  get 'trades/:flavour_id/new', controller: :trades, action: :new, as: :trade_flavour

end

app/models/flavour.rb
class Flavour < ActiveRecord::Base
  enum size: { small: 1, medium: 2, large: 3 }

  default_scope { order(:name) }
end

app/models/messenger.rb
require 'xmpp4r'
require 'xmpp4r/client'
include Jabber
class Messenger

  attr_reader :client

  def initialize
    @jabber_id = ENV['JID']
    @jabber_password = ENV['JID_PASSWORD']
    @jabber_server = ENV['JABBER_SERVER']
    @jabber_port = ENV['JABBER_PORT']
  end

  def connect
    @client = Client.new(JID.new(@jabber_id))
    @client.use_ssl = true
    @client.connect(@jabber_server, @jabber_port)
    @client.auth @jabber_password
  end

  def send_message(to, body)
    subject = 'Troca de Cápuslas Dolce Gusto'
    message = Message.new(to, body).set_type(:normal).set_subject(subject)
    @client.send message
  end

  def close
    @client.close
  end

end

app/models/trade.rb
class Trade < ActiveRecord::Base

  belongs_to :user
  belongs_to :flavour

  store :changes_for, accessors: [ :flavour_ids ], coder: JSON

  validates_presence_of :user_id, :flavour_id, :amount, :changes_for

  validates :amount, numericality: { only_integer: true, greather_than: 0 }

  after_save :send_message_to_traders

  def send_message_to_traders

    trades = Trade.where(flavour_id: self.flavour_ids.map{ |id| id.to_i}).where.not(id: self.id)
    if !trades.empty?
      messenger = Messenger.new
      messenger.connect

      trades.each do |trade|
        if trade.flavour_ids.map{ |id| id.to_i }.include?(self.flavour_id)
          msg = "#{trade.user.name} quer trocar #{pluralize( trade.amount, 'cápsula' )} de #{trade.flavour.name} que você deseja por cápsulas de #{self.flavour.name} que você possui."
          messenger.send_message(self.user.email.gsub('serpro.gov.br', 'sim.serpro.gov.br'), msg)

          msg = "#{self.user.name} quer trocar #{pluralize( self.amount, 'cápsula' )} de #{self.flavour.name} que você deseja por cápsulas de #{trade.flavour.name} que você possui."
          messenger.send_message(trade.user.email.gsub('serpro.gov.br', 'sim.serpro.gov.br'), msg)

        end
        messenger.close
      end

    end

  rescue => e
    Rails.logger.error { "#{e.message} #{e.backtrace.join("\n")}" }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include LDAP

  has_many :trades

  def self.authenticate(cpf, senha)

    # Inicializa as varíáveis com nil
    user = nil
    ldap_connection = nil

    # Recupera o DN do usuário que deseja fazer login
    dn = LDAP.get_user_dn(cpf)

    # Se o DN foi recuperado corretamente (CPF válido e existente no domínio), tenta estabelecer conexão com o DN obtido e a senha informada pelo usuário que deseja fazer login
    if dn
      ldap_connection = LDAP.ldap_connect(dn, senha)
    end

    # Se conseguiu logar corretamente com o DN e senha do usuário, prossegue e recupera dados do usuário no domínio
    if ldap_connection

      ldap_entry = LDAP.ldap_get_user(ldap_connection, cpf)

      if ldap_entry

        attributes = {:cpf => ldap_entry.uid[0], :name => ldap_entry.cn[0], :registration => ldap_entry.employeenumber[0],
                    :email => ldap_entry.mail[0], :phone_number => ldap_entry.telephonenumber[0], :area => ldap_entry.ou[0]}

        user = User.find_by_cpf(attributes[:cpf])

        #Caso o usuário ainda não exista na tabela, cadastra seus dados no sistema
        if user.nil?
          user = User.create(attributes)
        end

      end

    end

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate!

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  private
  def authenticated?
    !current_user.nil?
  end
  helper_method :authenticated?

  def authenticate!
    unless authenticated?
      session[:ref] = request.url
      redirect_to login_url, :alert => 'Você precisa estar autenticado para acessar esta página.'
    end
  end

end

app/controllers/flavours_controller.rb
class FlavoursController < ApplicationController

  def index
    @flavours = Flavour.all
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  skip_before_filter :authenticate!, :only => [:new, :create]

  def new
  end

  def create
    cpf = unmask_number(login_params[:cpf], '999.999.999-99')
    user = User.authenticate(cpf, login_params[:password])

    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      session[:user_id] = nil
      flash.now.alert = 'Erro na autenticação'
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    current_user = nil
    redirect_to root_url
  end

  private
    def login_params
      params.require(:login).permit(:cpf, :password)
    end

    def unmask_number(number, mask)
      if number != nil and !number.empty?
        length = (mask.gsub /[^0-9]/, "").length
        number = number.gsub /[^0-9]/, ""
        number = number.rjust length, '0'
      end
    end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController

  before_action :set_trade, only: [:edit, :update, :destroy]

  def index
    @trades = Trade.all
  end

  def new
    @trade = Trade.new(flavour_id: params[:flavour_id])
    @flavour = Flavour.find(params[:flavour_id])
    @flavours = Flavour.all.where.not(id: @flavour.id)
  end

  def create
    @trade = Trade.new(trade_params)
    @trade.user_id = current_user.id
    if @trade.save
      redirect_to trades_url, notice: 'Troca cadastrada com sucesso.'
    else
      @flavour = Flavour.find(params[:trade][:flavour_id])
      @flavours = Flavour.all.where.not(id: @flavour.id)
      render :new
    end
  end

  def edit
    @flavour = @trade.flavour
    @flavours = Flavour.all.where.not(id: @flavour.id)
  end

  def update

    if @trade.update(trade_params)
      redirect_to trades_url, notice: 'Troca atualizada com sucesso.'
    else
      @flavours = Flavour.all
      render :edit
    end
  end

  def destroy
    if @trade.user_id == current_user.id
      @trade.destroy
      message = 'Troca excluída com sucesso.'
    else
      message = 'Você não tem permissão para excluir essa troca.'
    end
    redirect_to trades_url, notice: message
  end

  private
    def trade_params
      params.require(:trade).permit(:flavour_id, :amount, flavour_ids: [] )
    end

    def set_trade
      @trade = Trade.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flavours_helper.rb
module FlavoursHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/flavours/index.html.erb
<h4>Sabores</h4>
<hr>
<table class="table table-bordered">
  <tr>
<% @flavours.each_with_index do |flavour, index| %>
  <% if index > 0  and index % 3 == 0 %>
  </tr>
  <tr>
  <% end %>
    <td>
      <div class="row">
        <div class="col-md-7">
          <%= flavour.name %> <br>
          <%= image_tag("#{flavour.url}.jpg", width: 150) %>
        </div>
        <div class="col-md-5">
          Doses: <%= flavour.amount %> <br>
          <%= image_tag("#{flavour.size}.png") %>
          <%= link_to '<i class="fa fa-exchange fa-lg"></i>'.html_safe, trade_flavour_url(flavour), class: 'btn btn-info', alt: 'Trocar' %>
        </div>
      </div>

    </td>
<% end %>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Troca de Cápsulas Dolce Gusto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p></p>
  <div class="content-fluid">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <% if current_user != nil %>
          <nav class="navbar navbar-inverse">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_url %>">Troca de Cápsulas Dolce Gusto</a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-navbar-collapse">
                <ul class="nav navbar-nav">
                  <li class="<%= 'active' if current_page?(flavours_url) %>">
                    <%= link_to 'Sabores', flavours_url %>
                  </li>
                  <li class="<%= 'active' if current_page?(trades_url) %>">
                    <%= link_to 'Trocas', trades_url %>
                  </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                  <li>
                    <p class="navbar-text">
                      <%= current_user.name %>
                    </p>
                  </li>
                  <li>
                    <%= link_to '<i class="fa fa-sign-out"></i>'.html_safe, logout_url, method: :delete, title: 'Sair' %>
                  </li>
                </ul>

              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>


</body>
</html>

app/views/login/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Troca de Cápsulas Dolce Gusto</h3>
    <hr>
    <p>
      A autenticação deve ser realizada utilizando a conta RHDS (CPF e senha utilizados no windows/linux).
    </p>
    <%= simple_form_for :login, url: authenticate_url , method: :post do |f| %>

      <%= f.input :cpf, :placeholder => 'Informe seu CPF', label: 'CPF', input_html: { class: 'cpf'} %>
      <%= f.input :password, as: :password, label: 'Senha', :placeholder => 'Informe sua senha' %>
      <%= f.submit 'Entrar', :class => 'btn btn-primary' %>

    <% end %>
  </div>
</div>

app/views/login/new.html.erb
<%= render :partial => 'form' %>

app/views/trades/_form.html.erb
<%= simple_form_for @trade do |f| %>
  <%= f.input :flavour_id, as: :hidden %>
  <%= f.label :flavour_ids, label: 'Trocar:' %> <br>
  <div class="row">
    <div class="col-md-4">
      <strong><%= @flavour.name %></strong> <br>
      <%= image_tag("#{@flavour.url}.jpg", width: 150) %>
    </div>
    <div class="col-md-4">
      <%= f.input :amount, as: :integer, input_html: { min:1, value: 1 } %>
    </div>
  </div>
  <%= f.label :flavour_ids, label: 'Por:' %>
  <%= f.input :changes_for, as: :hidden %>
  <div class="row">
    <% @flavours.each_with_index do |flavour, index| %>
      <% if index > 0 and  index % 3 == 0 %>
  </div>
  <div class="row">
      <% end %>
      <div class="col-md-4">
        <%= f.input :flavour_ids, label: false do %>
          <% if @trade.new_record? %>
            <%= check_box_tag 'trade[flavour_ids][]', flavour.id, false, id: "checkbox-flavour-id-#{flavour.id}" %>
          <% else %>
            <%= check_box_tag 'trade[flavour_ids][]', flavour.id, @trade.flavour_ids.map{ |id| id.to_i }.include?(flavour.id), id: "checkbox-flavour-id-#{flavour.id}" %>
          <% end %>
          <strong><%= flavour.name %></strong> <br>
          <%= image_tag "#{flavour.url}.jpg", width: 100, class: 'flavour-image', 'data-flavour-id': flavour.id %>
        <% end %>
      </div>
    <% end %>
  </div>
  <hr>
  <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  <%= link_to 'Cancelar', trades_url, class: 'btn btn-default' %>
<% end %>

app/views/trades/edit.html.erb
<h4>Editar troca</h4>
<hr>
<%= render 'form' %>

app/views/trades/index.html.erb
<h4>Trocas</h4>
<hr>
<p>
<%= link_to 'Nova troca', flavours_url, class: 'btn btn-primary' %>
</p>
<table class="table table-bordered table-striped">
  <tr>
    <th>Quem</th>
    <th>Troca</th>
    <th>Por</th>
    <th></th>
  </tr>
<% @trades.each do |trade| %>
  <tr>
    <td>
      <%= trade.user.name %> <br>
      <%= trade.user.phone_number %>
    </td>
    <td>
      <%= pluralize( trade.amount, 'cápsula' )%> de
      <%= trade.flavour.name %> <br>
      <%= image_tag "#{trade.flavour.url}.jpg", width: 100 %>
    </td>
    <td style="width: 400px">
      <% trade.flavour_ids.each do |flavour_id| %>
        <div style="float: left; padding: 5px;">
          <%= Flavour.find(flavour_id).name %> <br>
          <%= image_tag "#{Flavour.find(flavour_id).url}.jpg", width: 100 %>
        </div>
      <% end %>
    </td>
    <td>
      <% if trade.user_id == current_user.id %>
        <%= link_to '<i class="fa fa-pencil fa-2x"></i>'.html_safe, edit_trade_url(trade), class: 'btn btn-warning' %>
        <br><br>
        <%= link_to '<i class="fa fa-trash fa-2x"></i>'.html_safe, trade, method: :delete, class: 'btn btn-danger'%>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/trades/new.html.erb
<h4>Nova troca</h4>
<hr>
<%= render 'form' %>